import Head from 'next/head';
import Image from 'next/image';

import About from 'src/components/About';
import Layout from 'src/components/Layout';

import styles from '../styles/Home.module.scss';

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <About />
      </main>
    </>
  );
}
