import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Layout from 'src/components/Layout';

export default function About() {
  return (
    <>
      <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>About</main>
    </>
  );
}
