import React, { useRef } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

import Layout from 'src/components/Layout';
import MyName from 'src/components/MyName';

export default function Home() {
  const ref = useRef(null);
  React.useEffect(() => {
    import('@lottiefiles/lottie-player');
  });
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ display: 'flex' }}>
          <MyName />
          <lottie-player
            id="firstLottie"
            ref={ref}
            autoplay
            // controls
            loop
            mode="normal"
            src="/assets/lottieAnimations/codeTyping.json"
            style={{ width: '900px', height: '900px' }}></lottie-player>
          {/* <lottie-player
            id="firstLottie"
            ref={ref}
            autoplay
            // controls
            loop
            mode="normal"
            src="/assets/lottieAnimations/floorParticles.json"
            style={{ width: '900px', height: '900px' }}></lottie-player> */}
        </div>
      </main>
    </>
  );
}
