import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Layout from 'src/components/Layout';
import MyName from 'src/components/MyName';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MyName />
      </main>
    </>
  );
}
