import Head from 'next/head';
import Image from 'next/image';

import Projects from 'src/components/Projects';

import styles from '../styles/Home.module.scss';

export default function ProjectsPage() {
  return (
    <>
      <Head>
        <title>Projects page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Projects />
      </main>
    </>
  );
}
